name: Unity CI

on:
  push:
    tags:
      - "v*.*.*" # Triggers the workflow on version tags like v1.0.0

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targetPlatform: [StandaloneWindows64, WebGL]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache Library
        uses: actions/cache@v4
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}-${{ github.run_id }}
          restore-keys: |
            Library-${{ matrix.targetPlatform }}-

      - name: Build Project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.targetPlatform }}
          unityVersion: 6000.0.42f1

      - name: Zip Build
        run: |
          cd build/${{ matrix.targetPlatform }}
          zip -r ../../${{ matrix.targetPlatform }}.zip .

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ matrix.targetPlatform }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
